FROM node:12-alpine
WORKDIR /app
COPY . /app
RUN npm install
# RUN npm rebuild node-sass
# RUN npm run build
#RUN npm install -g pm2
ENV NODE_ENV=local
#CMD ["pm2-runtime", "process.json"]
CMD ["npm","run","dev"]